language: node_js
node_js:
  - "6"

addons:
  chrome: stable

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: XPEVBjA2PvOtQQvjrLoltMr+5eVw35nqX46OD7ACrTrppudeDhKB+iDcAGgYNTCAVNsN6reSkupy5XdOpF93P4J4hK9BZ46RUQ9+INR+reU/LpJdzjVQJqlOcCLdppkbmoJuUUiv6O2nJDOrDqmADbI5NMM08XPprnsGS1Re/2c=
  on:
    tags: true
    repo: ember-cli/loader.js

cache: yarn

script:
  - yarn test
